### ISSUE TITLE
moduleType proposal

### ISSUE THREAD

**Issue by robdodson** [bower/bower.json-spec#10]
@unscriptable just mentioned this (https://github.com/bower/bower.json-spec/pull/7#issuecomment-28308027)

Related to this I believe https://github.com/bower/bower/pull/934

`moduleType` would allow the developer to specify if their package is AMD, global, CJS, etc.

**Comment by cvrebert** [comment]
@desandro Could you please close this in light of https://github.com/bower/bower.json-spec/pull/13#issuecomment-87837605 ?
