### ISSUE TITLE
Basic authentication for HTTP URLs (zip, tarball) not possbile

### ISSUE THREAD

**Issue by peerb** [bower/bower.json-spec#25]
With the current implementation, passing username and password for a non GIT dependency (e.g. artifacts from nexus) is only possible by adding basic authentication to the dependency url itself. Which then would be eventually committed to a repository. Is there any hidden feature which would allow the url resolver to add a user specific authentication? A shorthand resolver using global username and password is also only available for git.

Am I doing it wrong or is there a chance of including a basic authentication into bower for zips and tarballs?

Thanks,
Peer

**Comment by airborn** [comment]
Any news on this one?

**Comment by operatino** [comment]
I'm also interested. Is there some option to be passed programmatically?

**Comment by sheerun** [comment]
Now it's possible with [Pluggable Resolvers](http://bower.io/docs/pluggable-resolvers/). Someone still needs to implement it, though.
