### ISSUE TITLE
Can `main` contain globs?

### ISSUE THREAD

**Issue by donaldpipowitch** [bower/bower.json-spec#30]
I know that `main` shouldn't be a directory, but can it be a glob to files?

Say instead of
````
"main": [
  "dist/template1.html",
  "dist/template2.html",
  "dist/app.js"
]
````
a shorter
````
"main": [
  "dist/*.html",
  "dist/app.js"
]
````
?

The question would be what `$ bower list --path` would return? The glob or the expanded paths? (Maybe it could be configured like `$ bower list --path --expand-glob`.)

**Comment by DataTables** [comment]
I would also be interested in an official line on this in the specification. Globs can be useful for including a bunch of images, although I can also see that not supporting globs might make a developer think a bit more about what is being included.

**Comment by cvrebert** [comment]
@desandro Could you close this since #43 has been merged?

**Comment by desandro** [comment]
Closing as "no." But the general issue is still up for discussion. We'll be evaluating a separate data point to list all files used, like `files` that could contain globs.
