### ISSUE TITLE
dependencies and devDependencies automatically pull the latest commit when url has #latest suffix ?

### ISSUE THREAD

**Issue by vikikamath** [bower/bower.json-spec#54]
For example in `bower.json` for devDependency or dependency one could have a following entry:

```javascript
{
...
"xyzlib": "git+https://example.com/path/to/xyzlib.git#<SHA-1>"
....
}
```
upon `bower update` or `bower install`, `bower.json` pulls the xyzlib specified by <SHA-1> as expected.

If the `xyzlib` has additional commits, to refer to the latest commit, the bower.json pointing to `xyzlib` requires to be updated everytime.

Instead if a tag like `#latest` is available (as shown below), then irrespective of number of commits xyzlib moves ahead, the `#latest` will always refer to the most recent commit.

```javascript
{
...
"xyzlib": "git+https://example.com/path/to/xyzlib.git#latest"
....
}
```

**Comment by sheerun** [comment]
Tags are assumed to be not changing. If `latest` is branch, then bower re-fetches it each time (try for example `#master)`.
