### ISSUE TITLE
Inconsistencies for version, main, ignore attributes

### ISSUE THREAD

**Issue by evil-shrike** [bower/bower.json-spec#55]
There're some inconsistencies in the spec and bower's (1.5) behavior:

* version 
It's stated that `version` in package.json is "Deprecated. Use git or svn tags instead.". Ok, how will bower determine version in case of pluggable resolvers? For an example when a resolver returns tar.gz archive. There're no "tags" in that case.

* bower shows warnings if a package's package.json has no `main` and `ignore` attributes:
```
bower xxx#0.22 invalid-meta xxx is missing "main" entry in bower.json
bower xxx#0.22 invalid-meta xxx is missing "ignore" entry in bower.json
```
But in the spec these attributes are marked as "Recommended" not "required".

**Comment by sheerun** [comment]
- Pluggable resolvers use `releases` function written by resolver's author to list releases (e.g. `[{ target: 'v1.0.0', version: '1.0.0' }]`). You don't need to use tags to extract those. Tags are specific to Bower.
- That's why they are warnings, not errors :)
